spring.application.name=AuthenticationAuthorizationBelC18
server.port=1004


spring.datasource.url=jdbc:mysql://localhost:3306/LearnerC18AuthDB?createDatabaseIfNotExist=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.username=root
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.security.user.name=user
spring.security.user.password=$2a$11$JL1SjFA4ck2o9du0mH/Abul/VbMyHiuQmYg7E3OmBV9ltp7xxT8CK